# Generated by Django 3.1 on 2020-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0002_remove_user_headimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
