# Generated by Django 3.1 on 2020-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0005_auto_20200810_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='headimg',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
