# Generated by Django 3.1 on 2020-08-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0006_auto_20200810_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
