# Generated by Django 3.1 on 2020-08-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0007_auto_20200810_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
